# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pbshipping
from pbshipping.models.parcel_protection_quote_request_shipment_info_parcel_info_commodity_list import ParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList  # noqa: E501
from pbshipping.rest import ApiException

class TestParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList(unittest.TestCase):
    """ParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pbshipping.models.parcel_protection_quote_request_shipment_info_parcel_info_commodity_list.ParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList()  # noqa: E501
        if include_optional :
            return ParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList(
                category_path = '0', 
                item_code = '0', 
                name = '0', 
                url = '0'
            )
        else :
            return ParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList(
                category_path = '0',
                item_code = '0',
                name = '0',
                url = '0',
        )

    def testParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList(self):
        """Test ParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
