# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pbshipping
from pbshipping.models.special_services_rule import SpecialServicesRule  # noqa: E501
from pbshipping.rest import ApiException

class TestSpecialServicesRule(unittest.TestCase):
    """SpecialServicesRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SpecialServicesRule
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pbshipping.models.special_services_rule.SpecialServicesRule()  # noqa: E501
        if include_optional :
            return SpecialServicesRule(
                special_service_id = 'ADSIG', 
                branded_name = '0', 
                category_id = '0', 
                category_name = '0', 
                trackable = True, 
                input_parameter_rules = [
                    pbshipping.models.services_parameter_rule.ServicesParameterRule(
                        name = '0', 
                        branded_name = '0', 
                        required = True, 
                        min_value = 1.337, 
                        max_value = 1.337, 
                        free_value = 1.337, 
                        format = '0', 
                        description = '0', )
                    ], 
                prerequisite_rules = [
                    pbshipping.models.prerequisite_rules.PrerequisiteRules(
                        special_service_codes = 'ADSIG', 
                        min_input_value = 1.337, )
                    ], 
                incompatible_special_services = 'ADSIG'
            )
        else :
            return SpecialServicesRule(
        )

    def testSpecialServicesRule(self):
        """Test SpecialServicesRule"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
