# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pitneybowes_shippingapi
from pitneybowes_shippingapi.models.services_parameter_rule import ServicesParameterRule  # noqa: E501
from pitneybowes_shippingapi.rest import ApiException

class TestServicesParameterRule(unittest.TestCase):
    """ServicesParameterRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ServicesParameterRule
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pitneybowes_shippingapi.models.services_parameter_rule.ServicesParameterRule()  # noqa: E501
        if include_optional :
            return ServicesParameterRule(
                name = '0', 
                branded_name = '0', 
                required = True, 
                min_value = 1.337, 
                max_value = 1.337, 
                free_value = 1.337, 
                format = '0', 
                description = '0'
            )
        else :
            return ServicesParameterRule(
        )

    def testServicesParameterRule(self):
        """Test ServicesParameterRule"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
