# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pbshipping
from pbshipping.models.parcel_protection_create_response import ParcelProtectionCreateResponse  # noqa: E501
from pbshipping.rest import ApiException

class TestParcelProtectionCreateResponse(unittest.TestCase):
    """ParcelProtectionCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ParcelProtectionCreateResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pbshipping.models.parcel_protection_create_response.ParcelProtectionCreateResponse()  # noqa: E501
        if include_optional :
            return ParcelProtectionCreateResponse(
                transaction_id = '0', 
                parcel_protection_reference_id = '0', 
                parcel_protection_date = '0', 
                parcel_protection_fees = 1.337, 
                parcel_protection_fees_currency_code = '0', 
                parcel_protection_fees_breakup = pbshipping.models.parcel_protection_create_response_parcel_protection_fees_breakup.ParcelProtectionCreateResponse_parcelProtectionFeesBreakup(
                    base_premium = 1.337, 
                    technology_fee = 1.337, )
            )
        else :
            return ParcelProtectionCreateResponse(
        )

    def testParcelProtectionCreateResponse(self):
        """Test ParcelProtectionCreateResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
