# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pitneybowes_shippingapi
from pitneybowes_shippingapi.models.tax import Tax  # noqa: E501
from pitneybowes_shippingapi.rest import ApiException

class TestTax(unittest.TestCase):
    """Tax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Tax
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pitneybowes_shippingapi.models.tax.Tax()  # noqa: E501
        if include_optional :
            return Tax(
                display_name = '0', 
                name = '0', 
                tax_amount = 1.337, 
                tax_rate = 1.337
            )
        else :
            return Tax(
        )

    def testTax(self):
        """Test Tax"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
