# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pbshipping
from pbshipping.models.parcel_protection_create_response_parcel_protection_fees_breakup import ParcelProtectionCreateResponseParcelProtectionFeesBreakup  # noqa: E501
from pbshipping.rest import ApiException

class TestParcelProtectionCreateResponseParcelProtectionFeesBreakup(unittest.TestCase):
    """ParcelProtectionCreateResponseParcelProtectionFeesBreakup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ParcelProtectionCreateResponseParcelProtectionFeesBreakup
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pbshipping.models.parcel_protection_create_response_parcel_protection_fees_breakup.ParcelProtectionCreateResponseParcelProtectionFeesBreakup()  # noqa: E501
        if include_optional :
            return ParcelProtectionCreateResponseParcelProtectionFeesBreakup(
                base_premium = 1.337, 
                technology_fee = 1.337
            )
        else :
            return ParcelProtectionCreateResponseParcelProtectionFeesBreakup(
        )

    def testParcelProtectionCreateResponseParcelProtectionFeesBreakup(self):
        """Test ParcelProtectionCreateResponseParcelProtectionFeesBreakup"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
