# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pbshipping
from pbshipping.api.tracking_api import TrackingApi  # noqa: E501
from pbshipping.rest import ApiException


class TestTrackingApi(unittest.TestCase):
    """TrackingApi unit test stubs"""

    def setUp(self):
        self.api = pbshipping.api.tracking_api.TrackingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_tracking_events(self):
        """Test case for add_tracking_events

        getTrackingDetails  # noqa: E501
        """
        pass

    def test_get_tracking_details(self):
        """Test case for get_tracking_details

        getTrackingDetails  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
