# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pitneybowes_shippingapi
from pitneybowes_shippingapi.api.manifests_api import ManifestsApi  # noqa: E501
from pitneybowes_shippingapi.rest import ApiException


class TestManifestsApi(unittest.TestCase):
    """ManifestsApi unit test stubs"""

    def setUp(self):
        self.api = pitneybowes_shippingapi.api.manifests_api.ManifestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_manifest(self):
        """Test case for create_manifest

        This operation creates an end-of-day manifest  # noqa: E501
        """
        pass

    def test_reprint_manifest(self):
        """Test case for reprint_manifest

        reprintManifest  # noqa: E501
        """
        pass

    def test_retry_manifest(self):
        """Test case for retry_manifest

        retryManifest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
