# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pbshipping
from pbshipping.models.customs_item import CustomsItem  # noqa: E501
from pbshipping.rest import ApiException

class TestCustomsItem(unittest.TestCase):
    """CustomsItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CustomsItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pbshipping.models.customs_item.CustomsItem()  # noqa: E501
        if include_optional :
            return CustomsItem(
                description = '0', 
                h_s_tariff_code = '0', 
                net_cost_method = 'NO_NET_COST', 
                origin_country_code = '0', 
                origin_state_province = '0', 
                preference_criterion = 'A', 
                producer_address = pbshipping.models.address.Address(
                    address_lines = [
                        '0'
                        ], 
                    carrier_route = '0', 
                    city_town = '0', 
                    company = '0', 
                    country_code = '0', 
                    delivery_point = '0', 
                    email = '0', 
                    name = '0', 
                    phone = '0', 
                    postal_code = '0', 
                    residential = True, 
                    state_province = '0', 
                    status = 'PARSED', 
                    tax_id = '0', 
                    tax_id_type = 'EIN', ), 
                producer_determination = 'NO_1', 
                producer_id = '0', 
                quantity = 56, 
                quantity_uom = '0', 
                unit_price = 1.337, 
                unit_weight = pbshipping.models.parcel_weight.ParcelWeight(
                    weight = 1.337, 
                    unit_of_measurement = 'GM', )
            )
        else :
            return CustomsItem(
                description = '0',
                origin_country_code = '0',
                quantity = 56,
                unit_price = 1.337,
                unit_weight = pbshipping.models.parcel_weight.ParcelWeight(
                    weight = 1.337, 
                    unit_of_measurement = 'GM', ),
        )

    def testCustomsItem(self):
        """Test CustomsItem"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
