# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pitneybowes_shippingapi
from pitneybowes_shippingapi.models.parcel_protection_policy_response_shipper_info_address import ParcelProtectionPolicyResponseShipperInfoAddress  # noqa: E501
from pitneybowes_shippingapi.rest import ApiException

class TestParcelProtectionPolicyResponseShipperInfoAddress(unittest.TestCase):
    """ParcelProtectionPolicyResponseShipperInfoAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ParcelProtectionPolicyResponseShipperInfoAddress
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pitneybowes_shippingapi.models.parcel_protection_policy_response_shipper_info_address.ParcelProtectionPolicyResponseShipperInfoAddress()  # noqa: E501
        if include_optional :
            return ParcelProtectionPolicyResponseShipperInfoAddress(
                street1 = '0', 
                street2 = '0', 
                street3 = '0', 
                city = '0', 
                region = '0', 
                country = '0', 
                postal_code = '0'
            )
        else :
            return ParcelProtectionPolicyResponseShipperInfoAddress(
        )

    def testParcelProtectionPolicyResponseShipperInfoAddress(self):
        """Test ParcelProtectionPolicyResponseShipperInfoAddress"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
