# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pitneybowes_shippingapi.configuration import Configuration


class ContainerManifestResponseData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'pb_container_id': 'str',
        'label_data': 'str'
    }

    attribute_map = {
        'pb_container_id': 'pbContainerId',
        'label_data': 'labelData'
    }

    def __init__(self, pb_container_id=None, label_data=None, local_vars_configuration=None):  # noqa: E501
        """ContainerManifestResponseData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._pb_container_id = None
        self._label_data = None
        self.discriminator = None

        if pb_container_id is not None:
            self.pb_container_id = pb_container_id
        if label_data is not None:
            self.label_data = label_data

    @property
    def pb_container_id(self):
        """Gets the pb_container_id of this ContainerManifestResponseData.  # noqa: E501


        :return: The pb_container_id of this ContainerManifestResponseData.  # noqa: E501
        :rtype: str
        """
        return self._pb_container_id

    @pb_container_id.setter
    def pb_container_id(self, pb_container_id):
        """Sets the pb_container_id of this ContainerManifestResponseData.


        :param pb_container_id: The pb_container_id of this ContainerManifestResponseData.  # noqa: E501
        :type: str
        """

        self._pb_container_id = pb_container_id

    @property
    def label_data(self):
        """Gets the label_data of this ContainerManifestResponseData.  # noqa: E501


        :return: The label_data of this ContainerManifestResponseData.  # noqa: E501
        :rtype: str
        """
        return self._label_data

    @label_data.setter
    def label_data(self, label_data):
        """Sets the label_data of this ContainerManifestResponseData.


        :param label_data: The label_data of this ContainerManifestResponseData.  # noqa: E501
        :type: str
        """

        self._label_data = label_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContainerManifestResponseData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ContainerManifestResponseData):
            return True

        return self.to_dict() != other.to_dict()
