# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pitneybowes_shippingapi.configuration import Configuration


class CrossBorderQuotesErrorsErrorsErrors(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'error_code': 'str',
        'error_description': 'str',
        'additional_info': 'str',
        'parameters': 'list[str]'
    }

    attribute_map = {
        'error_code': 'errorCode',
        'error_description': 'errorDescription',
        'additional_info': 'additionalInfo',
        'parameters': 'parameters'
    }

    def __init__(self, error_code=None, error_description=None, additional_info=None, parameters=None, local_vars_configuration=None):  # noqa: E501
        """CrossBorderQuotesErrorsErrorsErrors - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._error_code = None
        self._error_description = None
        self._additional_info = None
        self._parameters = None
        self.discriminator = None

        if error_code is not None:
            self.error_code = error_code
        if error_description is not None:
            self.error_description = error_description
        if additional_info is not None:
            self.additional_info = additional_info
        if parameters is not None:
            self.parameters = parameters

    @property
    def error_code(self):
        """Gets the error_code of this CrossBorderQuotesErrorsErrorsErrors.  # noqa: E501


        :return: The error_code of this CrossBorderQuotesErrorsErrorsErrors.  # noqa: E501
        :rtype: str
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this CrossBorderQuotesErrorsErrorsErrors.


        :param error_code: The error_code of this CrossBorderQuotesErrorsErrorsErrors.  # noqa: E501
        :type: str
        """

        self._error_code = error_code

    @property
    def error_description(self):
        """Gets the error_description of this CrossBorderQuotesErrorsErrorsErrors.  # noqa: E501


        :return: The error_description of this CrossBorderQuotesErrorsErrorsErrors.  # noqa: E501
        :rtype: str
        """
        return self._error_description

    @error_description.setter
    def error_description(self, error_description):
        """Sets the error_description of this CrossBorderQuotesErrorsErrorsErrors.


        :param error_description: The error_description of this CrossBorderQuotesErrorsErrorsErrors.  # noqa: E501
        :type: str
        """

        self._error_description = error_description

    @property
    def additional_info(self):
        """Gets the additional_info of this CrossBorderQuotesErrorsErrorsErrors.  # noqa: E501


        :return: The additional_info of this CrossBorderQuotesErrorsErrorsErrors.  # noqa: E501
        :rtype: str
        """
        return self._additional_info

    @additional_info.setter
    def additional_info(self, additional_info):
        """Sets the additional_info of this CrossBorderQuotesErrorsErrorsErrors.


        :param additional_info: The additional_info of this CrossBorderQuotesErrorsErrorsErrors.  # noqa: E501
        :type: str
        """

        self._additional_info = additional_info

    @property
    def parameters(self):
        """Gets the parameters of this CrossBorderQuotesErrorsErrorsErrors.  # noqa: E501


        :return: The parameters of this CrossBorderQuotesErrorsErrorsErrors.  # noqa: E501
        :rtype: list[str]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this CrossBorderQuotesErrorsErrorsErrors.


        :param parameters: The parameters of this CrossBorderQuotesErrorsErrorsErrors.  # noqa: E501
        :type: list[str]
        """

        self._parameters = parameters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CrossBorderQuotesErrorsErrorsErrors):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CrossBorderQuotesErrorsErrorsErrors):
            return True

        return self.to_dict() != other.to_dict()
