# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pbshipping.configuration import Configuration


class AddTrackingEvents(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'carrier': 'str',
        'references': 'list[AddTrackingEventsReferences]'
    }

    attribute_map = {
        'carrier': 'carrier',
        'references': 'references'
    }

    def __init__(self, carrier=None, references=None, local_vars_configuration=None):  # noqa: E501
        """AddTrackingEvents - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._carrier = None
        self._references = None
        self.discriminator = None

        if carrier is not None:
            self.carrier = carrier
        if references is not None:
            self.references = references

    @property
    def carrier(self):
        """Gets the carrier of this AddTrackingEvents.  # noqa: E501


        :return: The carrier of this AddTrackingEvents.  # noqa: E501
        :rtype: str
        """
        return self._carrier

    @carrier.setter
    def carrier(self, carrier):
        """Sets the carrier of this AddTrackingEvents.


        :param carrier: The carrier of this AddTrackingEvents.  # noqa: E501
        :type: str
        """

        self._carrier = carrier

    @property
    def references(self):
        """Gets the references of this AddTrackingEvents.  # noqa: E501


        :return: The references of this AddTrackingEvents.  # noqa: E501
        :rtype: list[AddTrackingEventsReferences]
        """
        return self._references

    @references.setter
    def references(self, references):
        """Sets the references of this AddTrackingEvents.


        :param references: The references of this AddTrackingEvents.  # noqa: E501
        :type: list[AddTrackingEventsReferences]
        """

        self._references = references

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddTrackingEvents):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AddTrackingEvents):
            return True

        return self.to_dict() != other.to_dict()
