# coding: utf-8

"""
    Shipping API

    Shipping API Sample.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@pb.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from pitneybowes_shippingapi.api_client import ApiClient
from pitneybowes_shippingapi.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class RateParcelsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def rate_parcel(self, shipment, **kwargs):  # noqa: E501
        """Use this operation to rate a parcel before you print and purchase a shipment label. You can rate a parcel for multiple services and multiple parcel types with a single API request.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.rate_parcel(shipment, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param Shipment shipment: Shipment request for Rates (required)
        :param bool x_pb_unified_error_structure: Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs.
        :param str x_pb_shipper_rate_plan: USPS Only. Shipper rate plan, if applicable. For more information, see [this FAQ](https://shipping.pitneybowes.com/faqs/rates.html#rate-plans-faq)
        :param str x_pb_integrator_carrier_id: USPS Only. Negotiated services rate, if applicable.
        :param str x_pb_shipper_carrier_account_id: UPS (United Parcel Service) Only. The unique identifier returned in the shipperCarrierAccountId field by the [Register an Existing Carrier Account](https://shipping.pitneybowes.com/api/post-carrier-accounts-register.html) API.
        :param bool include_delivery_commitment: When set to true, returns estimated transit time in days.
        :param str carrier: Cross-Border only. Required for PB Cross-Border. Set this to PBI.
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Shipment
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.rate_parcel_with_http_info(shipment, **kwargs)  # noqa: E501

    def rate_parcel_with_http_info(self, shipment, **kwargs):  # noqa: E501
        """Use this operation to rate a parcel before you print and purchase a shipment label. You can rate a parcel for multiple services and multiple parcel types with a single API request.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.rate_parcel_with_http_info(shipment, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param Shipment shipment: Shipment request for Rates (required)
        :param bool x_pb_unified_error_structure: Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs.
        :param str x_pb_shipper_rate_plan: USPS Only. Shipper rate plan, if applicable. For more information, see [this FAQ](https://shipping.pitneybowes.com/faqs/rates.html#rate-plans-faq)
        :param str x_pb_integrator_carrier_id: USPS Only. Negotiated services rate, if applicable.
        :param str x_pb_shipper_carrier_account_id: UPS (United Parcel Service) Only. The unique identifier returned in the shipperCarrierAccountId field by the [Register an Existing Carrier Account](https://shipping.pitneybowes.com/api/post-carrier-accounts-register.html) API.
        :param bool include_delivery_commitment: When set to true, returns estimated transit time in days.
        :param str carrier: Cross-Border only. Required for PB Cross-Border. Set this to PBI.
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(Shipment, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'shipment',
            'x_pb_unified_error_structure',
            'x_pb_shipper_rate_plan',
            'x_pb_integrator_carrier_id',
            'x_pb_shipper_carrier_account_id',
            'include_delivery_commitment',
            'carrier'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method rate_parcel" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'shipment' is set
        if self.api_client.client_side_validation and ('shipment' not in local_var_params or  # noqa: E501
                                                        local_var_params['shipment'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `shipment` when calling `rate_parcel`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'include_delivery_commitment' in local_var_params and local_var_params['include_delivery_commitment'] is not None:  # noqa: E501
            query_params.append(('includeDeliveryCommitment', local_var_params['include_delivery_commitment']))  # noqa: E501
        if 'carrier' in local_var_params and local_var_params['carrier'] is not None:  # noqa: E501
            query_params.append(('carrier', local_var_params['carrier']))  # noqa: E501

        header_params = {}
        if 'x_pb_unified_error_structure' in local_var_params:
            header_params['X-PB-UnifiedErrorStructure'] = local_var_params['x_pb_unified_error_structure']  # noqa: E501
        if 'x_pb_shipper_rate_plan' in local_var_params:
            header_params['X-PB-Shipper-Rate-Plan'] = local_var_params['x_pb_shipper_rate_plan']  # noqa: E501
        if 'x_pb_integrator_carrier_id' in local_var_params:
            header_params['X-PB-Integrator-CarrierId'] = local_var_params['x_pb_integrator_carrier_id']  # noqa: E501
        if 'x_pb_shipper_carrier_account_id' in local_var_params:
            header_params['X-PB-Shipper-Carrier-AccountId'] = local_var_params['x_pb_shipper_carrier_account_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'shipment' in local_var_params:
            body_params = local_var_params['shipment']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oAuth2ClientCredentials']  # noqa: E501

        return self.api_client.call_api(
            '/v1/rates', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Shipment',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
